/*
	Backup GUI
	© Alex Waugh 2000

	$Id: GUI.c,v 1.1 2000-11-04 20:18:17 AJW Exp $

 */

#include <stdlib.h>
#include "tboxlibs.wimp.h"
#include "tboxlibs.toolbox.h"
#include "tboxlibs.event.h"
#include "tboxlibs.wimplib.h"

#define WimpVersion    310

#define UNUSED(x) (x=x)

static  WimpPollBlock  poll_block;
static  MessagesFD     messages;
static  IdBlock        id_block;

/*
 * Event handler to be called when toolbox event 1
 * is generated (by click on the 'Quit' entry of
 * the iconbar menu.
 */

static int IconbarMenu_Quit(int event_code, ToolboxEvent *event, IdBlock *id_block,void *handle)
{
  event_code = event_code;
  event = event;
  id_block = id_block;
  handle = handle;

  exit(0);
  return(1);
}


static int Message_Quit(WimpMessage *message,void *handle)
{
	UNUSED(message);
	UNUSED(handle);

	exit(EXIT_SUCCESS);
	return 1;
}


int main(void)
{
	int    toolbox_events = 0,
           wimp_messages = 0,
           event_code;

    /*
     * register ourselves with the Toolbox.
     */

    toolbox_initialise (0, WimpVersion, &wimp_messages, &toolbox_events, "<Backup$Dir>",
                        &messages, &id_block, 0, 0, 0);


    /*
     * initialise the event library.
     */

    event_initialise (&id_block);

    event_set_mask (1+256);

    /*
     * register handler for toolbox event 1,
     * which is generated by the 'Quit' option on the
     * iconbar menu.  Also register message handlers
     * to quit properly when quit messages are
     * received from the wimp.
     */

    event_register_toolbox_handler(-1,1,IconbarMenu_Quit,NULL);
    event_register_message_handler(Wimp_MQuit,Message_Quit,NULL);

    /*
     * poll loop
     */

    while (TRUE)
    {
        event_poll (&event_code, &poll_block, 0);
    }
}
